### ISSUE TITLE
Skip Cutscene Source Code?

### ISSUE THREAD

**Issue by Aida-Enna** [KangasZ/DalamudPluginRepository#2]
Heya! I was curious why your Skip Cutscene plugin isn't open source? I'd like to recommend it to people I know but I can't do that in good faith as long as it's closed source (I'm sure you understand why). Thank you for your work 🙏

**Comment by KangasZ** [comment]
Only used the skip cutscene for friend usage to be honest since I was sick of giving them a dev plugin and explaining how to install it. Uploaded it to GitHub and setup the github workflow actions I've been manually doing up untill now. Feel free to checkout the source here: https://github.com/KangasZ/SkipCutscene

Hope this helps / you can safely recommend the plugin/repo to others. Thanks for bringing this to my attention.

**Comment by Aida-Enna** [comment]
Awesome! And yeah, I can definitely recommend it now, thank you! 👍
